// unit of work - wzorzec 
// wzorzec - repository

package Repository;

import java.sql.Connection;
import java.sql.SQLException; 
import HogwartLibrary.Author;
import mapper.AuthorMapper;

public class AuthorRepository extends RepoBase<Author> {

	public AuthorRepository(Connection connection, 

			AuthorMapper mapper) {

		super(connection, mapper);
	

	}

	

	@Override
	protected String tableName() {

		// TODO Auto-generated method stub

		return "Author";

	}

	@Override
	protected String createTableSql() {

		// TODO Auto-generated method stub

		return "CREATE TABLE Author("

				+ "idAuthor bigint GENERATED BY DEFAULT AS IDENTITY,"

				+ "name VARCHAR(20)," 

				+ "surname VARCHAR(20),"
                        
                                + "PRIMARY_KEY idAuthor,"

				+ ")";

	}

	@Override
	protected String insertSql() {

		// TODO Auto-generated method stub

		return "INSERT INTO Author (idAuthor, name, surname) VALUES (?, ?, ?)";

	}

	@Override
        protected String deleteSql() {

		// TODO Auto-generated method stub

		return "DELETE FROM Author WHERE idAuthor = ?";

	}

	@Override
	protected String updateSql() {

		// TODO Auto-generated method stub

		return "UPDATE Author SET idAuthor = ?, name = ?, surname = ? WHERE id = ?";

	}

	@Override
	protected String selectByIdSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM Author WHERE idAuthor=?";

	}

	@Override
	protected String selectAllSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM Author";

	}

	

	@Override
        protected void setupInsert(Author entity) throws SQLException {

		insert.setInt(1, entity.getIdAuthor());

		insert.setString(2, entity.getName());

		insert.setString(3, entity.getSurname());

		

	}



	@Override
	protected void setupUpdate(Author entity) throws SQLException {

		update.setDouble(1, entity.getIdAuthor());

		update.setString(2, entity.getName());

		update.setString(3, entity.getSurname());



}

}
