/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Repository;

import Relationship.BookToAuthor;
import java.sql.Connection;
import java.sql.SQLException;
import mapper.BookToAuthorMapper;

public class BookToAuthorRepository extends RepoBase<BookToAuthor>{


	public BookToAuthorRepository(Connection connection, 

			BookToAuthorMapper mapper) {

		super(connection, mapper);
	

	}

	

	@Override
	protected String tableName() {

		// TODO Auto-generated method stub

		return "BookToAuthor";

	}

	@Override
	protected String createTableSql() {

		// TODO Auto-generated method stub

		return "CREATE TABLE BookToAuthor("

				+ "idBookToAuthor bigint GENERATED BY DEFAULT AS IDENTITY,"

				+ "idBook bigint," 

				+ "idAuthor bigint,"
                        
                                + "PRIMARY_KEY (idBookToAuthor),"
                        
                                + "CONSTRAINT fk_idBook FOREIGN KEY (idBook) REFERENCES TheBook (idBook),"
                        
                                + "CONSTRAINT fk_idAuthor FOREIGN KEY (idAuthor) REFERENCES Author (idAuthor)"

				+ ")";

	}

	@Override
	protected String insertSql() {

		// TODO Auto-generated method stub

		return "INSERT INTO BookToAuthor (idBookToAuthor, idBook, idAuthor) VALUES (?, ?, ?)";

	}

	@Override
        protected String deleteSql() {

		// TODO Auto-generated method stub

		return "DELETE FROM BookToAuthor WHERE idBookToAuthor = ?";

	}

	@Override
	protected String updateSql() {

		// TODO Auto-generated method stub

		return "UPDATE BookToAuthor SET idBookToAuthor = ?, idBook = ?, idAuthor = ? WHERE idBookToAuthorS = ?";

	}

	@Override
	protected String selectByIdSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM BookToAuthor WHERE idBookToAuthor=?";

	}

	@Override
	protected String selectAllSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM BookToAuthor";

	}

	

	@Override
        protected void setupInsert(BookToAuthor entity) throws SQLException {

		insert.setInt(1, entity.getIdBookToAuthor());

		insert.setInt(2, entity.getIdBook());

		insert.setInt(3, entity.getIdAuthor());

	}

	@Override
	protected void setupUpdate(BookToAuthor entity) throws SQLException {

		update.setDouble(1, entity.getIdBookToAuthor());

		update.setInt(2, entity.getIdBook());

		update.setInt(3, entity.getIdAuthor());



}

}
