/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Repository;

import Relationship.BookToAuthor;
import Relationship.HistoryToBook;
import java.sql.Connection;
import java.sql.SQLException;
import mapper.HistoryToBookMapper;

/**
 *
 * @author Lenovo
 */
public class HistoryToBookRepository extends RepoBase<HistoryToBook>{
    
    	public HistoryToBookRepository(Connection connection, 

			HistoryToBookMapper mapper) {

		super(connection, mapper);
	

	}

	

	@Override
	protected String tableName() {

		// TODO Auto-generated method stub

		return "HistoryToBook";

	}

	@Override
	protected String createTableSql() {

		// TODO Auto-generated method stub

		return "CREATE TABLE HistoryToBook("

				+ "idHistoryToBook bigint GENERATED BY DEFAULT AS IDENTITY,"

				+ "idHistory bigint," 

				+ "idBook bigint,"
                        
                                + "PRIMARY_KEY (idHistoryToBook),"
                        
                                + "CONSTRAINT fk_idHistory FOREIGN KEY (idHistory) REFERENCES History (idHistory),"
                        
                                + "CONSTRAINT fk_idBook FOREIGN KEY (idBook) REFERENCES TheBook (idBook)"

				+ ")";

	}

	@Override
	protected String insertSql() {

		// TODO Auto-generated method stub

		return "INSERT INTO HistoryToBook (idHistoryToBook, idHistory, idBook) VALUES (?, ?, ?)";

	}

	@Override
        protected String deleteSql() {

		// TODO Auto-generated method stub

		return "DELETE FROM HistoryToBook WHERE idHistoryToBook = ?";

	}

	@Override
	protected String updateSql() {

		// TODO Auto-generated method stub

		return "UPDATE BookToAuthor SET idHistoryToBook = ?, idHistory = ?, idBook = ? WHERE idHistoryToBook = ?";

	}

	@Override
	protected String selectByIdSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM HistoryToBook WHERE idHistoryToBook=?";

	}

	@Override
	protected String selectAllSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM HistoryToBook";

	}

	

	@Override
        protected void setupInsert(HistoryToBook entity) throws SQLException {

		insert.setInt(1, entity.getIdHistoryToBook());

		insert.setInt(2, entity.getIdHistory());

		insert.setInt(3, entity.getIdBook());

	}

	@Override
	protected void setupUpdate(HistoryToBook entity) throws SQLException {

		update.setDouble(1, entity.getIdHistoryToBook());

		update.setInt(2, entity.getIdHistory());

		update.setInt(3, entity.getIdBook());



}

}
