/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Repository;

import Relationship.HistoryToUser;
import java.sql.Connection;
import java.sql.SQLException;
import mapper.HistoryToUserMapper;

/**
 *
 * @author Lenovo
 */
public class HistoryToUserRepository extends RepoBase<HistoryToUser>{
    
       	public HistoryToUserRepository(Connection connection, 

			HistoryToUserMapper mapper) {

		super(connection, mapper);
	

	}

	

	@Override
	protected String tableName() {

		// TODO Auto-generated method stub

		return "HistoryToUser";

	}

	@Override
	protected String createTableSql() {

		// TODO Auto-generated method stub

		return "CREATE TABLE HistoryToUser("

				+ "idHistoryToUser bigint GENERATED BY DEFAULT AS IDENTITY,"

				+ "idHistory bigint," 

				+ "idUser bigint,"
                        
                                + "PRIMARY_KEY (idHistoryToUser),"
                        
                                + "CONSTRAINT fk_idHistory FOREIGN KEY (idHistory) REFERENCES History (idHistory),"
                        
                                + "CONSTRAINT fk_idUser FOREIGN KEY (idUser) REFERENCES User (idUser)"

				+ ")";

	}

	@Override
	protected String insertSql() {

		// TODO Auto-generated method stub

		return "INSERT INTO HistoryToUser (idHistoryToBook, idHistory, idUser) VALUES (?, ?, ?)";

	}

	@Override
        protected String deleteSql() {

		// TODO Auto-generated method stub

		return "DELETE FROM HistoryToUser WHERE idHistoryToUser = ?";

	}

	@Override
	protected String updateSql() {

		// TODO Auto-generated method stub

		return "UPDATE BookToAuthor SET idHistoryToUser = ?, idHistory = ?, idUser = ? WHERE idHistoryToUser = ?";

	}

	@Override
	protected String selectByIdSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM HistoryToUser WHERE idHistoryToUser=?";

	}

	@Override
	protected String selectAllSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM HistoryToUser";

	}

	

	@Override
        protected void setupInsert(HistoryToUser entity) throws SQLException {

		insert.setInt(1, entity.getIdHistoryToUser());

		insert.setInt(2, entity.getIdHistory());

		insert.setInt(3, entity.getIdUser());

	}

	@Override
	protected void setupUpdate(HistoryToUser entity) throws SQLException {

		update.setDouble(1, entity.getIdHistoryToUser());

		update.setInt(2, entity.getIdHistory());

		update.setInt(3, entity.getIdUser());



}
    
}
