/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Repository;
import HogwartLibrary.TheBook;
import java.sql.Connection;
import java.sql.SQLException; 
import mapper.TheBookMapper;

public class TheBookRepository extends RepoBase<TheBook>{

	public TheBookRepository(Connection connection, 

			TheBookMapper mapper) {

		super(connection, mapper);

	}

	@Override
	protected String tableName() {

		// TODO Auto-generated method stub

		return "TheBook";

	}

	@Override
	protected String createTableSql() {

		// TODO Auto-generated method stub

		return "CREATE TABLE TheBook("

				+ "idBook bigint GENERATED BY DEFAULT AS IDENTITY,"
                        
                                + "ISBN bigint,"

				+ "title VARCHAR(20)," 

				+ "section VARCHAR(20),"
                        
                                + "availability boolean,"
                        
                                + "PRIMARY_KEY idBook,"
                        
                                + "UNOQUE_KEY ISBN,"

				+ ")";

	}

	@Override
	protected String insertSql() {

		// TODO Auto-generated method stub

		return "INSERT INTO TheBook (idBook, isbn, title, section, availability) VALUES (?, ?, ? ,?, ?)";

	}

	@Override
        protected String deleteSql() {

		// TODO Auto-generated method stub

		return "DELETE FROM TheBook WHERE idBook = ?";

	}

	@Override
	protected String updateSql() {

		// TODO Auto-generated method stub

		return "UPDATE TheBook SET isbn = ?, title = ?, section = ?, availability = ?  WHERE isbn = ?";

	}

	@Override
	protected String selectByIdSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM TheBook WHERE idBook =?";

	}

	@Override
	protected String selectAllSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM TheBook";

	}

	

	@Override
        protected void setupInsert(TheBook entity) throws SQLException {

		insert.setInt(1, entity.getISBN());

		insert.setString(2, entity.getTitle());

		insert.setString(3, entity.getSection());
                
                insert.setBoolean(4, entity.getAvailability());
                
                insert.setInt(5, entity.getIdBook());

		

	}



	@Override
	protected void setupUpdate(TheBook entity) throws SQLException {

		update.setInt(1, entity.getISBN());

		update.setString(2, entity.getTitle());

		update.setString(3, entity.getSection());
                
                update.setBoolean(4, entity.getAvailability());
                
                update.setInt(5, entity.getIdBook());



}

}