/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Repository;
import HogwartLibrary.Author;
import HogwartLibrary.History;
import java.sql.Connection;
import java.sql.ResultSet; 
import java.sql.SQLException; 
import java.sql.Statement; 
import java.sql.PreparedStatement;
import mapper.HistoryMapper;

public class HistoryRepository {


    private PreparedStatement insert; 
    private PreparedStatement delete; 
    private PreparedStatement update; 
    private final IRepository<History> HistoryRepository;

	public HistoryRepository(Connection connection, 



			IRepository<History> HistoryRepository) {

		super(connection, HistoryMapper);


	}

	

	@Override
	protected String tableName() {

		// TODO Auto-generated method stub

		return "History";

	}

	@Override
	protected String createTableSql() {

		// TODO Auto-generated method stub

		return "CREATE TABLE History("

				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"

				+ "userId int)," 

				+ "hire boolean),"
                        
                                + "TooLongHire boolean),"
                        
                                + "reservation boolean,"
                        
                                + "punishment int,"

				+ ")";

	}

	@Override
	protected String insertSql() {

		// TODO Auto-generated method stub

		return "INSERT INTO History INSERT INTO history(id, userId, hire, TooLongHire, reservation, punishment) VALUES (?, ?, ?, ?, ?, ?)";

	}

	@Override
        protected String deleteSql() {

		// TODO Auto-generated method stub

		return "DELETE FROM History WHERE ID = ?";

	}

	@Override
	protected String updateSql() {

		// TODO Auto-generated method stub

		return "UPDATE History SET id = ?, userId = ?, hire = ?, TooLongHire = ?, reservation = ?, punishment = ? WHERE id = ?";

	}

	@Override
	protected String selectByIdSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM History WHERE id=?";

	}

	@Override
	protected String selectAllSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM History";

	}

	

	@Override
        protected void setupInsert(History entity) throws SQLException {

		insert.setInt(1, entity.getId());

		insert.setInt(2, entity.getUserId());

		insert.setBoolean(4, entity.getHire());
                
                insert.setBoolean(5, entity.getTooLongHire());
                
                insert.setBoolean(6, entity.getReservation());
                
                insert.setInt(7, entity.getPunishment());

		

	}



	@Override
	protected void setupUpdate(History entity) throws SQLException {

		update.setDouble(1, entity.getId());

		update.setString(2, entity.getName());

		update.setBoolean(4, entity.getHire());
                
                update.setBoolean(5, entity.getTooLongHire());
                
                update.setBoolean(6, entity.getReservation());
                
                update.setInt(7, entity.getPunishment());



}

}
