/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Repository;
import HogwartLibrary.Author;
import HogwartLibrary.TheBook;
import java.sql.Connection;
import java.sql.ResultSet; 
import java.sql.SQLException; 
import java.sql.Statement; 
import java.sql.PreparedStatement;
import mapper.AuthorMapper;

public class TheBookRepository {
    

    private PreparedStatement insert; 
    private PreparedStatement delete; 
    private PreparedStatement update; 
    
    

    
    
    
	public TheBookRepository(Connection connection, 

			AuthorMapper mapper,

			IRepository<TheBook> TheBookRepository) {

		super(connection, mapper);
	

	}

	

	@Override
	protected String tableName() {

		// TODO Auto-generated method stub

		return "TheBook";

	}

	@Override
	protected String createTableSql() {

		// TODO Auto-generated method stub

		return "CREATE TABLE TheBook("

				+ "isbn bigint GENERATED BY DEFAULT AS IDENTITY,"

				+ "title VARCHAR(20)," 

				+ "section VARCHAR(20),"
                        
                                + "availability boolean,"

				+ ")";

	}

	@Override
	protected String insertSql() {

		// TODO Auto-generated method stub

		return "INSERT INTO TheBook (isbn, title, section, availability) VALUES (?, ? ,?, ?)";

	}

	@Override
        protected String deleteSql() {

		// TODO Auto-generated method stub

		return "DELETE FROM TheBook WHERE ID = ?";

	}

	@Override
	protected String updateSql() {

		// TODO Auto-generated method stub

		return "UPDATE TheBook SET isbn = ?, title = ?, section = ?, availability = ?  WHERE isbn = ?";

	}

	@Override
	protected String selectByIdSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM TheBook WHERE id=?";

	}

	@Override
	protected String selectAllSql() {

		// TODO Auto-generated method stub

		return "SELECT * FROM TheBook";

	}

	

	@Override
        protected void setupInsert(TheBook entity) throws SQLException {

		insert.setInt(1, entity.getISBN());

		insert.setString(2, entity.getTitle());

		insert.setString(3, entity.getSection());
                
                insert.setBoolean(4, entity.getAvailability());

		

	}



	@Override
	protected void setupUpdate(TheBook entity) throws SQLException {

		update.setInt(1, entity.getISBN());

		update.setString(2, entity.getTitle());

		update.setString(3, entity.getSection());
                
                update.setBoolean(4, entity.getAvailability());



}

}